#---------------------------
# Fluid
# Author: Fluid-dev organization
# Github: https://github.com/fluid-dev/hexo-theme-fluid
#
# æœ¬é…ç½®çš„è¯¦ç»†æŒ‡å—è¯·è§ï¼šhttps://fluid-dev.github.io/hexo-fluid-docs/guide/
#---------------------------


#---------------------------
# å…¨å±€
# Site
#---------------------------
favicon: /img/favicon.png # ç½‘ç«™æ ‡ç­¾é¡µçš„ icon

apple_touch_icon: /img/apple-touch-icon.png # ç”¨äºè‹¹æœè®¾å¤‡çš„ icon

title_join_string: ' ~ '  # æµè§ˆå™¨æ ‡ç­¾é¡µä¸­çš„æ ‡é¢˜åˆ†éš”ç¬¦ï¼Œæ•ˆæœï¼š æ–‡ç« å ~ ç«™ç‚¹å

force_https: false  # å¼ºåˆ¶æ‰€æœ‰é“¾æ¥å‡çº§ä¸º HTTPSï¼ˆé€‚ç”¨äºå›¾ç‰‡ç­‰èµ„æºå‡ºç° HTTP æ··å…¥æŠ¥é”™ï¼‰

highlight: # ä»£ç é«˜äº®
  enable: true
  theme: tomorrow-night-eighties # available: github-v2 | tomorrow | tomorrow-night | tomorrow-night-eightiesï¼Œæ›´å¤šä¸»é¢˜å¯ä» https://jmblog.github.io/color-themes-for-google-code-prettify/ è·å–ï¼Œä¿å­˜ä¸º `*.min.css` åˆ° `source/lib/prettify/`ï¼Œåœ¨å…¶ä¸­ .prettyprint{ background: ***; ...} çš„background å€¼ååŠ ä¸Š !importantï¼Œä¾‹å¦‚ï¼š.prettyprint{background:#fafbfc!important; ...}

fun_features: # ä¸€äº›å¥½ç©çš„åŠŸèƒ½
  typing: # ä¸º subtitle æ·»åŠ æ‰“å­—æœºæ•ˆæœ
    enable: true
    typeSpeed: 70 # æ‰“å°é€Ÿåº¦
    cursorChar: "_" # æ¸¸æ ‡å­—ç¬¦
    loop: false # æ˜¯å¦å¾ªç¯æ’­æ”¾æ•ˆæœ
  anchorjs: # ä¸ºæ–‡ç« å†…å®¹ä¸­çš„æ ‡é¢˜æ·»åŠ é”šå›¾æ ‡
    enable: true
    element: h1,h2,h3,h4,h5,h6
    placement: right # iconæ”¾ç½®çš„ä½ç½®ï¼š left | right
    visible: false # é»˜è®¤æ‚¬æµ®æ˜¾ç¤ºï¼Œå¯é€‰ï¼šalwaysï¼ˆä¸€ä¼šæ˜¾ç¤ºï¼‰ | touchï¼ˆç§»åŠ¨ç«¯è§¦æ‘¸æ˜¾ç¤ºï¼‰
    icon: "" # å¯é€‰ï¼šÂ§ | # | â¡ ç­‰ï¼Œç•™ç©ºåˆ™ä¸ºé»˜è®¤æ•ˆæœ
  mouse_click:  # é¼ æ ‡ç‚¹å‡»åŠ¨æ•ˆ
    enable: true
    style: love # ç›®å‰è®¾ç½®ä¸¤ä¸ªå€¼ï¼švaluesï¼ˆä»·å€¼è§‚è¯æ±‡ï¼‰ | loveï¼ˆçˆ±å¿ƒï¼‰

color:  # ä¸»ä½“é¢œè‰²é…ç½®ï¼Œå¯ä»¥ä»è¿™é‡Œå¯»æ‰¾å¯å‘ï¼š https://www.webdesignrankings.com/resources/lolcolors/
  body_bg_color: "#eee"
  navbar_bg_color: "#2f4154"
  navbar_text_color: "white"
  text_color: "#3c4858"
  link_color: "#3c4858"
  link_hover_color: "#1abc9c"
  board_color: "#fff"

web_analytics:  # ç½‘é¡µè®¿é—®ç»Ÿè®¡
  enable: false
  baidu:  # ç™¾åº¦ç»Ÿè®¡çš„Keyï¼Œå‚è§ https://tongji.baidu.com/sc-web/10000033910/home/site/getjs?siteId=13751376 ä»£ç è·å–ä¸­ hm.js? åè¾¹çš„å­—ç¬¦ä¸²
  google:  # Googleç»Ÿè®¡çš„Tracking IDï¼Œå‚è§ https://analytics.google.com/analytics/web/
  tencent:  # è…¾è®¯ç»Ÿè®¡çš„H5 App idï¼Œå‚è§ https://mta.qq.com/h5/manage/ctr_app_manage
  woyaola:  # 51.laç«™ç‚¹ç»Ÿè®¡IDï¼Œå‚è§ https://www.51.la/user/site/index
  cnzz:  # å‹ç›Ÿ/cnzzç«™ç‚¹ç»Ÿè®¡web_idï¼Œå‚è§ https://web.umeng.com/main.php?c=site&a=show

lazyload: # å¯¹é¡µé¢ä¸­çš„å›¾ç‰‡è¿›è¡Œæ‡’åŠ è½½å¤„ç†ï¼Œå¯è§èŒƒå›´å¤–çš„å›¾ç‰‡ä¸ä¼šåŠ è½½
  enable: true
  onlypost: false  # ä»…åœ¨æ–‡ç« é¡µä½¿ç”¨æ‡’åŠ è½½

smooth_scroll: # å¹³æ»‘æ»šåŠ¨æ•ˆæœ
  enable: true

daovoice:  # åœ¨çº¿å®¢æœ Daovoice å‚è€ƒï¼šhttp://dashboard.daovoice.io
  enable: false # æ˜¯å¦å¼€å¯åœ¨çº¿å®¢æœèŠå¤©
  appid: ''  # åº”ç”¨IDè®¾ç½®

#---------------------------
# é¡µå¤´
# Header
#---------------------------
navbar:
  blog_title:  # å¯¼èˆªæ å·¦ä¾§çš„æ ‡é¢˜ï¼Œä¸ºç©ºåˆ™æŒ‰ hexo config.title æ˜¾ç¤º
  menu:  # å¯è‡ªè¡Œå¢å‡ï¼Œè‹¥æƒ³å‡å»æŸä¸ªå…¥å£ï¼Œå¯ä»¥å°†å€¼ç•™ç©ºï¼Œæ˜¾ç¤ºæ–‡æœ¬å…³è” languages
    home: /
    archive: /archives/
    category: /categories/
    tag: /tags/
    about: /about/
    #links: /links/  # å‹é“¾é¡µï¼ŒæŠŠå‰é¢#å»æ‰å³å¯å±•ç¤º

search: # æœç´¢æ 
  enable: true
  path: /local-search.xml # æ–‡ä»¶å¼•ç”¨åœ°å€ï¼Œé»˜è®¤æ˜¯ä¸‹æ–¹ç”Ÿæˆä½ç½®ï¼Œä¹Ÿå¯ä»¥å°†ç”Ÿæˆåçš„ local-search.xml ä¸Šä¼ åˆ°å…¶å®ƒä½ç½®å¼•ç”¨ï¼Œå¦‚ï¼šhttps://www.example.com/local-search.xml
  generate_path: /local-search.xml # æ–‡ä»¶ç”Ÿæˆä½ç½®ï¼Œå¿…é¡»ä¸ºç›¸å¯¹ä½ç½®
  field: post
  content: true

scroll_down_arrow:  # å‘ä¸‹æ»šåŠ¨çš„ç®­å¤´
  enable: true
  banner_height_limit: 90  # å¤´å›¾é«˜åº¦ä¸å°äºæŒ‡å®šæ¯”ä¾‹ï¼Œæ‰æ˜¾ç¤ºç®­å¤´
  scroll_after_turning_page: true  # ç¿»é¡µåè‡ªåŠ¨æ»šåŠ¨

banner_parallax: true  # å¤´å›¾æ»šåŠ¨è§†å·®


#---------------------------
# é¡µè„š
# Footer
#---------------------------
footer:
  statistics:  # ç»Ÿè®¡ç½‘ç«™ PVã€UVï¼Œä½¿ç”¨çš„æ˜¯ä¸è’œå­ï¼Œæ˜¾ç¤ºåœ¨é¡µè„š
    enable: false
    pv_format: "æ€»è®¿é—®é‡ {} æ¬¡"  # æ˜¾ç¤ºçš„æ–‡æœ¬ï¼Œ{}æ˜¯æ•°å­—çš„å ä½ç¬¦ï¼ˆå¿…é¡»åŒ…å«)ï¼Œä¸‹åŒ
    uv_format: "æ€»è®¿å®¢æ•° {} äºº"

  beian:  # The footer of China's website policy, other areas keep disable
    enable: false
    icp_text: äº¬ICPè¯123456å· # ICPè¯å·
    police_text: äº¬å…¬ç½‘å®‰å¤‡12345678å· # å…¬å®‰å¤‡æ¡ˆå·ï¼Œä¸å¡«åˆ™åªæ˜¾ç¤ºICP
    police_code: 12345678 # å…¬å®‰å¤‡æ¡ˆçš„ç¼–å·ï¼Œç”¨äºURLè·³è½¬æŸ¥è¯¢
    police_icon: /img/police_beian.png # å…¬å®‰å¤‡æ¡ˆçš„å›¾ç‰‡. ä¸ºç©ºæ—¶ä¸æ˜¾ç¤ºå¤‡æ¡ˆå›¾ç‰‡

scroll_top_arrow:  # å‘é¡¶éƒ¨æ»šåŠ¨çš„ç®­å¤´
  enable: true


#---------------------------
# é¦–é¡µ
# Index Page
#---------------------------
index:
  banner_img: /img/default.png  # é¦–é¡µ Banner å¤´å›¾ï¼Œä»¥ä¸‹ç›¸åŒ
  banner_img_height: 100  # å¤´å›¾é«˜åº¦ï¼Œå±å¹•ç™¾åˆ†æ¯”ï¼Œavailable: 0 - 100
  slogan:  # é¦–é¡µå‰¯æ ‡é¢˜çš„ç‹¬ç«‹è®¾ç½®
    enable: true  # ä¸º false åˆ™ä¸æ˜¾ç¤ºä»»ä½•å†…å®¹
    text:  Stay hungry, stay foolish. # ä¸ºç©ºåˆ™æŒ‰ hexo config.subtitle æ˜¾ç¤º
  auto_excerpt:
    enable: true
  post_url_target: _self  # available: _blank | _self
  post_meta: # æ˜¯å¦æ˜¾ç¤ºæ–‡ç« ä¿¡æ¯ï¼ˆæ—¶é—´ã€åˆ†ç±»ã€æ ‡ç­¾ï¼‰
    date: true
    category: true
    tag: true


#---------------------------
# æ–‡ç« é¡µ
# Post Page
#---------------------------
post:
  banner_img: /img/default.png
  banner_img_height: 70  # available: 0 - 100
  meta:  # æ–‡ç« æ ‡é¢˜ä¸‹æ–¹çš„ä¿¡æ¯
    date:  # æ–‡ç« æ—¥æœŸ
      enable: true
      format: "dddd, MMMM Do YYYY, h:mm a"  # æ ¼å¼å‚ç…§ ISO-8601 æ—¥æœŸæ ¼å¼åŒ–
    wordcount:  # å­—æ•°ç»Ÿè®¡
      enable: true
      format: "{} å­—"  # æ˜¾ç¤ºçš„æ–‡æœ¬ï¼Œ{}æ˜¯æ•°å­—çš„å ä½ç¬¦ï¼ˆå¿…é¡»åŒ…å«)ï¼Œä¸‹åŒ
    min2read:  # é˜…è¯»æ—¶é—´
      enable: true
      format: "{} åˆ†é’Ÿ"
    views:  # é˜…è¯»æ¬¡æ•°ï¼Œç»Ÿè®¡åŸºäºä¸è’œå­
      enable: true
      format: "{} æ¬¡"
  toc:  # å³ä¾§å¯¼èˆªæ¡
    enable: true
  copyright:  # ç‰ˆæƒå£°æ˜
    enable: true
    content: 'æœ¬åšå®¢æ‰€æœ‰æ–‡ç« é™¤ç‰¹åˆ«å£°æ˜å¤–ï¼Œå‡é‡‡ç”¨ <a href="https://zh.wikipedia.org/wiki/Wikipedia:CC_BY-SA_3.0%E5%8D%8F%E8%AE%AE%E6%96%87%E6%9C%AC" rel="nofollow noopener">CC BY-SA 3.0åè®®</a> ã€‚è½¬è½½è¯·æ³¨æ˜å‡ºå¤„ï¼'
  custom:  # æ–‡ç« åº•éƒ¨è‡ªå®šä¹‰å†…å®¹
    enable: false
    content: '<img src="https://octodex.github.com/images/jetpacktocat.png" class="rounded mx-auto d-block mt-5" style="width:150px; height:150px;">' # è‡ªå®šä¹‰åŒºåŸŸï¼Œæ”¯æŒ HTMLï¼Œå¯è‡ªè¡Œæ’å…¥èµèµç ã€å…¬ä¼—å·äºŒç»´ç ç­‰å†…å®¹
  comments:  # è¯„è®º
    enable: true  # å¼€å¯è¯„è®º
    type: gitalk  # æŒ‡å®šä½¿ç”¨çš„è¯„è®ºæ¨¡å—  available: disqus | valine | gitalk | utterances | changyan | livere
  image_zoom:  # æ–‡ç« å›¾ç‰‡å¯ç‚¹å‡»æ”¾å¤§
    enable: true
  math:  # æ•°å­¦å…¬å¼ï¼Œå¼€å¯ä¹‹å‰éœ€è¦æ›´æ¢ Markdown æ¸²æŸ“å™¨ï¼Œå¦åˆ™å¤æ‚å…¬å¼ä¼šæœ‰å…¼å®¹é—®é¢˜ï¼Œå…·ä½“è¯·è§ https://fluid-dev.github.io/hexo-fluid-docs/guide/#æ•°å­¦å…¬å¼
    enable: false
    specific: false  # å¼€å¯åï¼Œåªæœ‰åœ¨æ–‡ç«  Front-matter é‡ŒæŒ‡å®š `math: true` æ‰ä¼šåœ¨æ–‡ç« é¡µå¯åŠ¨å…¬å¼è½¬æ¢ï¼Œä»¥ä¾¿åœ¨é¡µé¢ä¸åŒ…å«å…¬å¼æ—¶æé«˜åŠ è½½é€Ÿåº¦
    engine: mathjax  # å…¬å¼å¼•æ“  available: mathjax | katex

#---------------------------
# è¯„è®º
# Comments
#---------------------------

# å¼€å¯è¯„è®ºåœ¨ä¸Šæ–¹çš„ post.comments é…ç½®

# utterances
# You can install utterances with https://utteranc.es/ and generate your configuration
utterances:
  repo:
  issue_term:
  label: utterances
  theme: github-light
  crossorigin: anonymous

# Disqus
disqus:
  shortname: # your shortname

# Gitalk
# You can get yout ClientID and ClientSecret from https://github.com/settings/applications/new
# More info available at https://github.com/gitalk/gitalk#options
gitalk:
  clientID: cbf8fb8a51aff41416e3                    # GitHub Application Client ID
  clientSecret: b5b2229a80bf94074fbe53aa502edefd17a2ab9c                # GitHub Application Client Secret
  repo: happy-yuxuan.github.io                        # The repo to store comments
  owner: happy-yuxuan                       # GitHub repository owner. Can be personal user or organization.
  admin: happy-yuxuan                       # GitHub repo owner and collaborators, only these guys can initialize github issues, should be like "['admin']" or "['admin1','admin2']"
  id: location.pathname         # The unique id of the page. Length must less than 50.
  language: zh-CN               # Localization language key, en, zh-CN and zh-TW are currently available.
  labels: "['Gitalk']"          # GitHub issue labels.
  perPage: 15                   # Pagination size, with maximum 100.
  pagerDirection: last          # Comment sorting direction, available values are last and first.
  distractionFreeMode: false    # Facebook-like distraction free mode.
  createIssueManually: true     # By default, Gitalk will create a corresponding github issue for your every single page automatically when the logined user is belong to the admin users. You can create it manually by setting this option to true.

# Valine
# You can get your appid and appkey from https://leancloud.cn
# More info available at https://valine.js.org
valine:
  appid:  # your leancloud application appid
  appkey:  # your leancloud application appkey
  notify: false # mail notifier, See: https://github.com/xCss/Valine/wiki
  verify: false # Verification code
  placeholder: è¯´ç‚¹ä»€ä¹ˆ # comment box placeholder
  avatar: retro # gravatar style https://valine.js.org/avatar.html
  pageSize: 10 # pagination size

# Changyan
# You can get your appid from http://changyan.kuaizhan.com/setting/common/isv-mgr
# Install: http://changyan.kuaizhan.com/static/help/f-fitself.html
changyan:
  appid: ''            # your changyan application appid        # ç•…è¨€ID
  conf: ''             # conf                                   # ç•…è¨€è®¾ç½®
  notify: false        # beian warning message                  # å¤‡æ¡ˆæç¤º
  libopen: true        # open laboratory                        # ç•…è¨€å®éªŒå®¤åŠŸèƒ½å¼€å…³
  cyEmoji: true        # comments emoji                         # è¯„è®ºè¡¨æƒ…
  cyWallsplugin: true  # Hot text matching                      # çƒ­æ–‡é…å›¾
  cyReping: true       # hot comments                           # çƒ­é—¨è¯„è®º
  cyReward: true       # reward                                 # æ‰“èµ
  cyQing: true         # Light comment                          # è½»è¯„è®º
  cyHotusers: true     # User evaluation                        # çƒ­è¯„ç”¨æˆ·
  cyHotnews: true      # Hot news                               # çƒ­é—¨æ–°é—»
  cyHotnewswall: true  # News wall                              # æ–°é—»å¢™
  cyPk: ''             # Topic debate                           # è¾©è®º
  cyPoll: true         # vote                                   # æŠ•ç¥¨
  cyBarrage: true      # Picture barrage                        # å›¾ç‰‡å¼¹å¹•
  cyTvbarrage: true    # Video barrage                          # è§†é¢‘å¼¹å¹•

# Livere æ¥å¿…åŠ›
# You can get your uid from https://www.livere.com/my_Livere
livere:
  uid: ''            # your livere application uid        # æ¥å¿…åŠ›ID


#---------------------------
# å½’æ¡£é¡µ
# Archive Page
#---------------------------
archive:
  banner_img: /img/default.png
  banner_img_height: 80  # available: 0 - 100


#---------------------------
# åˆ†ç±»å½’æ¡£é¡µ
# Categories Page
#---------------------------
category:
  banner_img: /img/default.png
  banner_img_height: 80  # available: 0 - 100


#---------------------------
# æ ‡ç­¾å½’æ¡£é¡µ
# Tags Page
#---------------------------
tag:
  banner_img: /img/default.png
  banner_img_height: 80  # available: 0 - 100
  tagcloud: # æ ‡ç­¾äº‘
    min_font: 15
    max_font: 30
    unit: px  # å­—å·å•ä½
    start_color: "#BBBBEE"
    end_color: "#337ab7"


#---------------------------
# å…³äºé¡µ
# About Page
#---------------------------
about:  # ä»¥ä¸‹ä»…ä¸ºé¡µé¢é¡¶éƒ¨çš„åŸºæœ¬ä¿¡æ¯ï¼Œæ›´å¤šå†…å®¹è¯·åœ¨ ./pages/about.md ä¸­ç¼–è¾‘ï¼Œæ”¯æŒ markdown å’Œ HTML
  md_path: ./pages/about.md  # å…³äºé¡µæ–‡æ¡£çš„ç›¸å¯¹è·¯å¾„ï¼Œå¯ä»¥æŒ‰ç›¸å¯¹æ–‡æ¡£è®¾ç½®ä¸»é¢˜ä¹‹å¤–çš„è·¯å¾„ï¼Œä»è€Œé¿å…æ›´æ–°å†²çª
  banner_img: /img/default.png
  banner_img_height: 80  # available: 0 - 100
  avatar: /img/avatar.jpg # å¤´åƒ
  name: Victor
  introduce: ä¸€ä¸ªå­¦ç”Ÿ / çˆ±æ‰“ä»£ç  / çˆ±æ‰“ç½‘çƒğŸ¾ # æ”¯æŒ HTML
  icons: # æ›´å¤šå›¾æ ‡å¯ä» https://fontawesome.com/v5.10.0/icons?d=gallery æŸ¥æ‰¾ï¼Œå¹¶ä»¥ "å›¾æ ‡å: url" çš„æ ¼å¼æ·»åŠ åœ¨ä¸‹æ–¹
    "fas fa-mail-bulk": mailto://happyvictorwu@outlook.com
    "fab fa-linkedin": https://www.linkedin.com/in/wuyuxuan/?locale=en_US
    "fab fa-github": https://github.com/happy-yuxuan
    "fab fa-zhihu": https://www.zhihu.com/people/lai-zi-cheng-xu-yuan-shen-shen-de-e-yi
    "fab fa-weixin": # å¾®ä¿¡å›¾æ ‡ï¼Œè¿™ä¸ªæ˜¯ç‰¹æ®Šå›¾æ ‡ï¼Œç‚¹å‡»ä¸ä¼šè·³è½¬è€Œæ˜¯æ‚¬æµ®äºŒç»´ç ï¼Œæ‰€ä»¥é“¾æ¥éœ€è¦å¯¹åº”äºŒç»´ç å›¾ç‰‡åœ°å€


#---------------------------
# 404é¡µ
# 404 Page
#---------------------------
page404:
  banner_img: /img/default.png
  banner_img_height: 80  # available: 0 - 100
  subtitle: 'Page not found'


#---------------------------
# å‹é“¾é¡µ
# Links Page
#---------------------------
links:
  banner_img: /img/default.png
  banner_img_height: 80  # available: 0 - 100
  items:
    Fluid Docs: [https://fluid-dev.github.io/hexo-fluid-docs/, ä¸»é¢˜ä½¿ç”¨æŒ‡å—]
    Fluid Repo: [https://github.com/fluid-dev/hexo-theme-fluid, ä¸»é¢˜ GitHub ä»“åº“]
    Fluid Changelog: [https://github.com/fluid-dev/hexo-theme-fluid/blob/master/Changelog.md, ä¸»é¢˜æ›´æ–°æ—¥å¿—]
